-- 2024.05.10 (금)
-- 직원별 소유하고 있는 자산종류별 건수 조회 -> MAX(D.SEQ_NO)의 USE_EMP_NO 가져오도록 수정
;
SELECT U.USER_NM AS '직원명'
       ,SUM(CASE WHEN M.ASST_KND_CD = '101' THEN 1 ELSE 0 END) AS '소프트웨어 - Office'
       ,SUM(CASE WHEN M.ASST_KND_CD = '102' THEN 1 ELSE 0 END) AS '소프트웨어 - OS'
       ,SUM(CASE WHEN M.ASST_KND_CD = '103' THEN 1 ELSE 0 END) AS '소프트웨어 - 한컴오피스'
       ,SUM(CASE WHEN M.ASST_KND_CD = '201' THEN 1 ELSE 0 END) AS '노트북'
       ,SUM(CASE WHEN M.ASST_KND_CD = '202' THEN 1 ELSE 0 END) AS '데스크탑'
       ,SUM(CASE WHEN M.ASST_KND_CD = '203' THEN 1 ELSE 0 END) AS '모니터'
       ,SUM(CASE WHEN M.ASST_KND_CD = '204' THEN 1 ELSE 0 END) AS '저장매체'
       ,SUM(CASE WHEN M.ASST_KND_CD = '205' THEN 1 ELSE 0 END) AS '빔프로젝터'
       ,SUM(CASE WHEN M.ASST_KND_CD = '206' THEN 1 ELSE 0 END) AS '스마트보드'
       ,SUM(CASE WHEN M.ASST_KND_CD = '207' THEN 1 ELSE 0 END) AS '외장형 ODD'
FROM (
		SELECT ASST.ASST_NO  AS ASST_NO
		       ,ASST.INST_CD AS INST_CD
		       ,ASST.ASST_KND_CD AS ASST_KND_CD
		       ,D.USE_EMP_NO AS USE_EMP_NO
		  FROM (
					SELECT M.ASST_NO AS ASST_NO
					       ,M.INST_CD AS INST_CD
					       ,M.ASST_KND_CD AS ASST_KND_CD
					       ,MAX(D.SEQ_NO) AS SEQ_NO
					FROM TCOM023_ASST_AMN_M M 
					LEFT OUTER JOIN TCOM024_ASST_USE_D D
					ON M.INST_CD = D.INST_CD
				  AND M.ASST_NO = D.ASST_NO
				WHERE M.INST_CD = '001'
				GROUP BY M.ASST_NO, M.INST_CD, M.ASST_KND_CD
		       ) ASST
		  LEFT OUTER JOIN TCOM024_ASST_USE_D D
		    ON ASST.INST_CD = D.INST_CD
		   AND ASST.ASST_NO = D.ASST_NO
		   AND D.SEQ_NO = ASST.SEQ_NO
     ) M
 INNER JOIN TUSR001_USER U
    ON M.INST_CD = U.INST_CD
   AND M.USE_EMP_NO = U.EMP_NO 
 GROUP BY U.USER_NM  
 ORDER BY U.USER_NM
 ;
-- 쿼리  2가지 방법
SELECT ED.*, C.CD
 FROM TCOM010_EMP_DEPT ED
 LEFT OUTER JOIN TCOM002_CODE C
   ON ED.INST_CD = C.INST_CD
  AND C.CD_GRP_ID = '012' 
  AND ED.DUTY_CD = C.CD
WHERE C.CD IS NULL;

SELECT ED.*, C.CD
FROM TCOM010_EMP_DEPT ED
LEFT OUTER JOIN TCOM002_CODE C
 ON ED.INST_CD = C.INST_CD
AND C.CD_GRP_ID = '012'
AND ED.DUTY_CD = C.CD
WHERE NOT EXISTS (SELECT C2.CD
                    FROM TCOM002_CODE C2
                   WHERE ED.INST_CD = C2.INST_CD
                     AND C2.CD_GRP_ID = '012'
                     AND ED.DUTY_CD = C2.CD
                  );
