-- 1번
WITH RECURSIVE DEPT AS (
		SELECT DEPT_LVL_CD
		       ,DEPT_CD
		       ,DEPT_NM
		       ,convert(DEPT_NM, CHAR(1000)) AS path
		       ,DEPT_ORD
		  FROM TCOM003_DEPT
		 WHERE INST_CD = '001'
		   AND DEPT_LVL_CD = 1
		 UNION ALL 
		SELECT D.DEPT_LVL_CD
		       ,D.DEPT_CD
		       ,D.DEPT_NM
		       ,concat(A.path, '-', D.DEPT_NM) AS path
		       ,D.DEPT_ORD
		  FROM TCOM003_DEPT D
		 INNER JOIN DEPT A
		    ON D.UPPER_DEPT_CD = A.DEPT_CD
)
SELECT DEPT.DEPT_NM
       ,DEPT.path
       ,SUM(DE.EMP_CNT)
  FROM (
		 SELECT  D.DEPT_LVL_CD
		        ,D.DEPT_NM  
		        ,D.path
		        ,COUNT(ED.EMP_NO) AS EMP_CNT
		   FROM DEPT D
		  LEFT OUTER JOIN TCOM010_EMP_DEPT ED
		    ON D.DEPT_CD = ED.DEPT_CD
		  GROUP BY D.path, D.DEPT_NM,D.DEPT_LVL_CD
) DE
 LEFT OUTER JOIN DEPT  DEPT
   ON DE.path LIKE CONCAT('%', DEPT.DEPT_NM, '%')
 GROUP BY DEPT.DEPT_NM ,DEPT.path
 ORDER BY DEPT.path
; 


-- 2번 
SELECT M.ASST_NO AS 자산번호
       ,C.CD_NM AS 자산종류
       ,M.SEQ_NO AS SEQ
       ,D.CD_NM AS 자산상태명
       ,U.USER_NM AS 직원명
       ,DEP.DEPT_NM AS 부서명
FROM (
		SELECT M.ASST_NO AS ASST_NO
		       ,M.INST_CD AS INST_CD
		       ,M.ASST_KND_CD AS ASST_KND_CD
		       ,MAX(D.ASST_STS_CD) AS ASST_STS_CD
		       ,MAX(D.SEQ_NO) AS SEQ_NO
		       ,MAX(D.USE_EMP_NO) AS USE_EMP_NO
		  FROM TCOM023_ASST_AMN_M M 
		 INNER JOIN TCOM024_ASST_USE_D D
		    ON M.INST_CD = D.INST_CD
		   AND M.ASST_NO = D.ASST_NO
		 GROUP BY M.ASST_NO, M.INST_CD ,M.ASST_KND_CD
     ) M
 INNER JOIN TCOM002_CODE C
    ON M.INST_CD = C.INST_CD
   AND C.CD_GRP_ID = '052'
   AND M.ASST_KND_CD = C.CD
 INNER JOIN TCOM002_CODE D
    ON M.INST_CD = D.INST_CD
   AND D.CD_GRP_ID = '053'
   AND M.ASST_STS_CD = D.CD
 INNER JOIN TUSR001_USER U
    ON M.INST_CD = U.INST_CD
   AND M.USE_EMP_NO = U.EMP_NO
 INNER JOIN TCOM010_EMP_DEPT ED
    ON M.INST_CD = ED.INST_CD
   AND U.EMP_NO = ED.EMP_NO
   AND ED.MAIN_DEPT_YN = 'Y'
 INNER JOIN TCOM003_DEPT DEP
    ON M.INST_CD = DEP.INST_CD
   AND ED.DEPT_CD = DEP.DEPT_CD
 ORDER BY M.ASST_NO
;
-- 3번 

 
SELECT CERT.DEPT_NM
       ,CO.CD_NM
       ,SUM(CERT_TP_CD_2023) AS '2023(건수)'
       ,SUM(CERT_TP_CD_2024) AS '2024(건수)'
  FROM (
	SELECT  D.INST_CD AS INST_CD
	       ,D.DEPT_NM AS DEPT_NM
	       ,C1.CERT_TP_CD AS CERT_TP_CD_2023
	       ,C2.CERT_TP_CD AS CERT_TP_CD_2024
	  FROM TCOM003_DEPT D
	  LEFT OUTER JOIN TCOM010_EMP_DEPT ED
	    ON D.INST_CD = ED.INST_CD
	   AND D.DEPT_CD = ED.DEPT_CD
	  LEFT OUTER JOIN TUSR001_USER U
	    ON D.INST_CD = U.INST_CD
	   AND ED.EMP_NO = U.EMP_NO
	  LEFT OUTER JOIN TUSR012_CERT C1
	    ON D.INST_CD = C1.INST_CD
	   AND ED.EMP_NO = C1.EMP_NO
	   AND SUBSTR(C1.CERT_DT, 1,4) = '2023'
	  LEFT OUTER JOIN TUSR012_CERT C2
	    ON D.INST_CD = C2.INST_CD
	   AND ED.EMP_NO = C2.EMP_NO
	   AND SUBSTR(C2.CERT_DT, 1,4) = '2024'
	 GROUP BY D.INST_CD, D.DEPT_NM,C1.CERT_TP_CD, C2.CERT_TP_CD
) CERT  
  LEFT OUTER JOIN TCOM002_CODE CO
     ON CO.CD_GRP_ID = '023'
    AND (CERT.CERT_TP_CD_2023 = CO.CD 
	      OR CERT.CERT_TP_CD_2024 = CO.CD)
  WHERE CERT.INST_CD = '001'
    AND CO.CD_NM IS NOT NULL
  GROUP BY CERT.DEPT_NM,CERT.INST_CD, CO.CD_NM
  ORDER BY CERT.DEPT_NM
  ;


-- 4번 
SELECT U.USER_NM
       ,CASE WHEN C.CERT_TP_CD = '01' THEN 'Y' ELSE 'N' END AS CERT_1
       ,CASE WHEN C.CERT_TP_CD = '02' THEN 'Y' ELSE 'N' END AS CERT_2
       ,CASE WHEN C.CERT_TP_CD = '03' THEN 'Y' ELSE 'N' END AS CERT_3
       ,UOS.GIVE_OFF_DAYS
       ,UOS.USE_OFF_DAYS
  FROM TUSR001_USER U
  LEFT OUTER JOIN TUSR012_CERT C
    ON C.INST_CD = U.INST_CD
	AND C.EMP_NO = U.EMP_NO
  LEFT OUTER JOIN TUSR002_USER_OFF_STATUS UOS
    ON U.INST_CD = UOS.INST_CD
   AND U.EMP_NO = UOS.EMP_NO
	AND BASE_YY = '2024';
