--오늘의 쿼리문제는 TCOM006_APPR_D (결재상세) 로 현재 최종결재상태를 조회하는 문제입니다.
--    > 결재번호 | 최종결재상태명 | 최종승인결재직원명 | 진행중이면 진행중인결재직원명
--    > 진행중은 (대기, 진행중) 으로 봅니다.
--    > 진행중의 직원명은 결재순서 가장먼저인 직원을 조회하면됩니다.

SELECT * FROM TCOM006_APPR_D;
 WHERE APPR_NO = '002A202300114';
SELECT * 
  FROM TCOM001_CODE_GROUP 
 WHERE CD_GRP_ID = '015'
   AND INST_CD = '001';
SELECT * FROM TCOM002_CODE 
 WHERE CD_GRP_ID = '015'
   AND INST_CD = '001';
SELECT * FROM TUSR001_USER;

SELECT A.APPR_NO AS 결재번호 
       ,CASE WHEN C.CD IN ('01','02') THEN '진행중'
		       ELSE C.CD_NM
			END AS 최종결재상태명 
       ,CASE WHEN C.CD IN ('01','02') THEN ''
		       ELSE U.USER_NM 
			END AS 최종승인결재직원명
       ,CASE WHEN C.CD IN ('01','02') THEN U.USER_NM
		       ELSE ''
			END AS 진행중인결재직원명
  FROM TCOM006_APPR_D A
  LEFT OUTER JOIN TCOM002_CODE C
    ON A.INST_CD = C.INST_CD 
   AND A.APPR_ST_CD = C.CD
	AND C.CD_GRP_ID = '015'
  LEFT OUTER JOIN TUSR001_USER U
    ON A.INST_CD = U.INST_CD 
   AND A.APPR_EMP_NO = U.EMP_NO
 WHERE A.INST_CD = '001'
 ORDER BY A.APPR_NO;

SELECT A.APPR_NO 
       ,CASE WHEN C.CD IN ('01','02') THEN '진행중'
		       ELSE C.CD_NM
			END AS 최종결재상태명
       ,CASE WHEN C.CD IN ('01','02') THEN D.USER_NM
		       ELSE U.USER_NM 
			END AS 최종승인결재직원명
       ,CASE WHEN C.CD IN ('01','02') THEN U.USER_NM
		       ELSE ''
			END AS 진행중인결재직원명
  FROM (
		SELECT APPR_NO 
		      ,INST_CD
		      ,MAX(APPR_ORD) AS APPR_ORD
		  FROM TCOM006_APPR_D
		  GROUP BY INST_CD, APPR_NO
		 HAVING INST_CD = '001'
  ) A
  LEFT OUTER JOIN TCOM006_APPR_D B
    ON A.APPR_NO = B.APPR_NO
   AND A.INST_CD = B.INST_CD
   AND A.APPR_ORD = B.APPR_ORD
  LEFT OUTER JOIN TCOM002_CODE C
    ON B.INST_CD = C.INST_CD 
   AND B.APPR_ST_CD = C.CD
	AND C.CD_GRP_ID = '015'
  LEFT OUTER JOIN TUSR001_USER U
    ON A.INST_CD = U.INST_CD 
   AND B.APPR_EMP_NO = U.EMP_NO
 WHERE A.INST_CD = '001'
 ORDER BY A.APPR_NO   
  ;
  
SELECT A.APPR_NO 
       ,CASE WHEN A.APPR_ST_CD IN ('01','02') THEN ''
		       ELSE U1.USER_NM
			END AS EMP_NO_LST
       ,CASE WHEN A.APPR_ST_CD IN ('01','02') THEN U2.USER_NM
		       ELSE ''
			END AS EMP_NO_FST
		 ,A.APPR_ST_CD
  FROM (
			SELECT APPR_NO 
			      ,INST_CD
			      ,APPR_ST_CD
			      ,MAX(APPR_ORD) AS APPR_ORD_MAX
					,MIN(APPR_ORD) AS APPR_ORD_MIN
			  FROM TCOM006_APPR_D
			 GROUP BY INST_CD, APPR_NO, APPR_ST_CD
			 HAVING INST_CD = '001'
  ) A
  LEFT OUTER JOIN TCOM006_APPR_D B
    ON A.APPR_NO = B.APPR_NO
   AND A.INST_CD = B.INST_CD
   AND A.APPR_ORD_MAX = B.APPR_ORD
  LEFT OUTER JOIN TCOM006_APPR_D C
    ON A.APPR_NO = C.APPR_NO
   AND A.INST_CD = C.INST_CD
   AND  A.APPR_ORD_MIN = C.APPR_ORD
  LEFT OUTER JOIN TUSR001_USER U1
    ON A.INST_CD = U1.INST_CD 
   AND B.APPR_EMP_NO = U1.EMP_NO
  LEFT OUTER JOIN TUSR001_USER U2
    ON A.INST_CD = U2.INST_CD 
   AND C.APPR_EMP_NO = U2.EMP_NO
 WHERE A.INST_CD = '001'
;

--결재번호 별로 1개씩 나오게 수정
SELECT APPR.APPR_NO
       ,MAX(APPR.APPR_ST_CD)
       ,MAX(APPR.EMP_NO_LST)
       ,MAX(APPR.EMP_NO_FST)
  FROM (
		SELECT A.APPR_NO  AS APPR_NO
		       ,CASE WHEN A.APPR_ST_CD IN ('01','02') THEN ''
				       ELSE U1.USER_NM
					END AS EMP_NO_LST
		       ,CASE WHEN A.APPR_ST_CD IN ('01','02') THEN U2.USER_NM
				       ELSE ''
					END AS EMP_NO_FST
				 ,A.APPR_ST_CD AS APPR_ST_CD
		  FROM (
					SELECT APPR_NO 
					      ,INST_CD
					      ,APPR_ST_CD
					      ,MAX(APPR_ORD) AS APPR_ORD_MAX
							,MIN(APPR_ORD) AS APPR_ORD_MIN
					  FROM TCOM006_APPR_D
					 GROUP BY INST_CD, APPR_NO, APPR_ST_CD
					 HAVING INST_CD = '001'
		  ) A
		  LEFT OUTER JOIN TCOM006_APPR_D B
		    ON A.APPR_NO = B.APPR_NO
		   AND A.INST_CD = B.INST_CD
		   AND A.APPR_ORD_MAX = B.APPR_ORD
		  LEFT OUTER JOIN TCOM006_APPR_D C
		    ON A.APPR_NO = C.APPR_NO
		   AND A.INST_CD = C.INST_CD
		   AND  A.APPR_ORD_MIN = C.APPR_ORD
		  LEFT OUTER JOIN TUSR001_USER U1
		    ON A.INST_CD = U1.INST_CD 
		   AND B.APPR_EMP_NO = U1.EMP_NO
		  LEFT OUTER JOIN TUSR001_USER U2
		    ON A.INST_CD = U2.INST_CD 
		   AND C.APPR_EMP_NO = U2.EMP_NO
		 WHERE A.INST_CD = '001'
  		)APPR
  	GROUP BY APPR.APPR_NO;
  	
-- INST_CD 수정하여 쿼리 보내드립니다.
SELECT 
    APPR.APPR_NO
    ,MAX(CASE WHEN APPR.APPR_ST_CD IN ('01', '02') THEN '진행중' ELSE '승인' END) AS ST
    ,MAX(CASE WHEN APPR.APPR_ST_CD IN ('01', '02') THEN '' ELSE APPR.EMP_NO_LST END) AS EMP_NO_LST
    ,MAX(CASE WHEN APPR.APPR_ST_CD IN ('01', '02') THEN APPR.EMP_NO_FST ELSE '' END) AS EMP_NO_FST
FROM (
    SELECT 
        A.APPR_NO AS APPR_NO
        ,CASE WHEN A.APPR_ST_CD IN ('01', '02') THEN '' ELSE U1.USER_NM END AS EMP_NO_LST
        ,CASE WHEN A.APPR_ST_CD IN ('01', '02') THEN U2.USER_NM ELSE '' END AS EMP_NO_FST
        ,A.APPR_ST_CD AS APPR_ST_CD
    FROM (
        SELECT 
            APPR_NO
            ,INST_CD
            ,APPR_ST_CD
            ,MAX(APPR_ORD) AS APPR_ORD_MAX
            ,MIN(APPR_ORD) AS APPR_ORD_MIN
        FROM TCOM006_APPR_D
        GROUP BY INST_CD, APPR_NO, APPR_ST_CD
    ) A
    LEFT OUTER JOIN TCOM006_APPR_D B 
	   ON A.APPR_NO = B.APPR_NO 
	  AND A.INST_CD = B.INST_CD 
	  AND A.APPR_ORD_MAX = B.APPR_ORD
    LEFT OUTER JOIN TCOM006_APPR_D C 
	   ON A.APPR_NO = C.APPR_NO 
	  AND A.INST_CD = C.INST_CD 
	  AND A.APPR_ORD_MIN = C.APPR_ORD
    LEFT OUTER JOIN TUSR001_USER U1 
	   ON A.INST_CD = U1.INST_CD 
	  AND B.APPR_EMP_NO = U1.EMP_NO
    LEFT OUTER JOIN TUSR001_USER U2 
	   ON A.INST_CD = U2.INST_CD 
	  AND C.APPR_EMP_NO = U2.EMP_NO
  -- WHERE A.INST_CD = '001'
  WHERE A.APPR_NO = '001A202300046'
) APPR
GROUP BY APPR.APPR_NO;
  	
  	