-- 2024.05.23 (목)
-- 1. 멸종위기의 대장균 찾기
  WITH RECURSIVE ED AS (
SELECT ID /* 재귀함수로 세대 구하기(부모ID = 재귀세대ID) */
       ,PARENT_ID
       ,1 AS GENERATION
  FROM ECOLI_DATA
 WHERE PARENT_ID IS NULL   
 UNION ALL 
SELECT E2.ID
       ,E2.PARENT_ID
       ,1 + E1.GENERATION AS GENERATION
  FROM ED E1
 INNER JOIN ECOLI_DATA E2
    ON E2.PARENT_ID = E1.ID 
)
SELECT COUNT(ID) AS COUNT /* 각 세대별로 NULL이 아닌 부모ID를 제외한 ID 개수 조회 */
       ,GENERATION
  FROM ED
 WHERE ID NOT IN(SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL) 
 GROUP BY GENERATION
 ORDER BY GENERATION; /* 꼭 다시 풀어보기 */




-- 2. 상품을 구매한 회원 비율 구하기
WITH UI AS (
SELECT *
  FROM USER_INFO
 WHERE YEAR(JOINED) = '2021' /* 2021년에 가입한 사용자 */
)
SELECT YEAR(O.SALES_DATE) AS YEAR
       ,MONTH(O.SALES_DATE) AS MONTH
       ,COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS
       ,ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM UI),1) AS PUCHASED_RATIO /* (구매이력 사용자 수) / (년,월별 사용자 수) */
  FROM UI U
 INNER JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
 WHERE O.USER_ID IN (SELECT USER_ID FROM UI)   /* 2021년 가입한 사용자 중 구매이력이 있는 사용자 */
 GROUP BY YEAR, MONTH
 ORDER BY YEAR, MONTH;

